/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;
import model.*;
import javax.swing.*;
import java.awt.CardLayout;

/**
 *
 * @author 56111
 */
public class ProfileMngWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ProfileDirectory profileDirectory;
    
    /**
     * Creates new form PersonMngWorkAreaJPanel
     */
    public ProfileMngWorkAreaJPanel(JPanel userProcessContainer, ProfileDirectory profileDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.profileDirectory = profileDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateProfile = new javax.swing.JButton();
        btnManageProfiles = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchByLName = new javax.swing.JTextField();
        btnSearchByFName = new javax.swing.JButton();
        btnSearchByStreetAddress = new javax.swing.JButton();
        txtSearchByFName = new javax.swing.JTextField();
        txtSearchByStreetAddress = new javax.swing.JTextField();
        btnSearchByLName = new javax.swing.JButton();

        setBackground(new java.awt.Color(176, 190, 197));

        btnCreateProfile.setText("Create Profile");
        btnCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfileActionPerformed(evt);
            }
        });

        btnManageProfiles.setText("Manage Profiles");
        btnManageProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfilesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person Profile Manager");

        btnSearchByFName.setText("Search First Name:");
        btnSearchByFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByFNameActionPerformed(evt);
            }
        });

        btnSearchByStreetAddress.setText("Search Street Address:");
        btnSearchByStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByStreetAddressActionPerformed(evt);
            }
        });

        btnSearchByLName.setText("Search Last Name:");
        btnSearchByLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByLNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearchByStreetAddress)
                                    .addComponent(btnSearchByFName)
                                    .addComponent(btnSearchByLName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearchByStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchByFName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSearchByLName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateProfile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnManageProfiles)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateProfile, btnManageProfiles, btnSearchByFName, btnSearchByLName, btnSearchByStreetAddress});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtSearchByFName, txtSearchByLName, txtSearchByStreetAddress});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProfile)
                    .addComponent(btnManageProfiles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchByFName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnSearchByLName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByStreetAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchByFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtSearchByLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchByStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfileActionPerformed
        // TODO add your handling code here:
        CreateProfileJPanel panel = new CreateProfileJPanel(userProcessContainer, profileDirectory);
        userProcessContainer.add("AccountMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateProfileActionPerformed

    private void btnManageProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfilesActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel panel = new ManageProfileJPanel(userProcessContainer, profileDirectory);
        userProcessContainer.add("AccountMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageProfilesActionPerformed

    private void btnSearchByFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByFNameActionPerformed
        // TODO add your handling code here:
        if(txtSearchByFName.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the first name to search.","Warning" ,JOptionPane.WARNING_MESSAGE);
        }
        else{
            String searchKey = txtSearchByFName.getText();
            Profile foundProfile = profileDirectory.searchByFName(searchKey);
            if(foundProfile != null){
                System.out.println("Profile found:");
                System.out.println(foundProfile.getFirstName() + foundProfile.getLastName());
                ViewProfileJPanel panel = new ViewProfileJPanel(userProcessContainer, profileDirectory, foundProfile);
                userProcessContainer.add("ViewProfileJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                JOptionPane.showMessageDialog(null, "Profile not found. Please check the input and try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchByFNameActionPerformed

    private void btnSearchByStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByStreetAddressActionPerformed
        // TODO add your handling code here:
        if(txtSearchByStreetAddress.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the street address to search.","Warning" ,JOptionPane.WARNING_MESSAGE);
        }
        else{
            String searchKey = txtSearchByStreetAddress.getText();
            Profile foundProfile = profileDirectory.searchByStreetAddress(searchKey);
            if(foundProfile != null){
                ViewProfileJPanel panel = new ViewProfileJPanel(userProcessContainer, profileDirectory, foundProfile);
                userProcessContainer.add("ViewProfileJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                JOptionPane.showMessageDialog(null, "Profile not found. Please check the input and try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchByStreetAddressActionPerformed

    private void btnSearchByLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByLNameActionPerformed
        // TODO add your handling code here:
        if(txtSearchByLName.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter the last name to search.","Warning" ,JOptionPane.WARNING_MESSAGE);
        }
        else{
            String searchKey = txtSearchByLName.getText();
            Profile foundProfile = profileDirectory.searchByLName(searchKey);
            if(foundProfile != null){
                ViewProfileJPanel panel = new ViewProfileJPanel(userProcessContainer, profileDirectory, foundProfile);
                userProcessContainer.add("ViewProfileJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                JOptionPane.showMessageDialog(null, "Profile not found. Please check the input and try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchByLNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton btnManageProfiles;
    private javax.swing.JButton btnSearchByFName;
    private javax.swing.JButton btnSearchByLName;
    private javax.swing.JButton btnSearchByStreetAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSearchByFName;
    private javax.swing.JTextField txtSearchByLName;
    private javax.swing.JTextField txtSearchByStreetAddress;
    // End of variables declaration//GEN-END:variables
}
