/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.*;
import ui.PersonManager.*;
import java.awt.CardLayout;

/**
 *
 * @author 56111
 */
public class MainJFrame extends javax.swing.JFrame {

    private ProfileDirectory profileDirectory;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.profileDirectory = new ProfileDirectory();
        for(int i = 0; i<7; i++){
           generateDemoData(i); 
        }
        
    }
    
    private void generateDemoData(int index){
        Profile newProfile = profileDirectory.addProfile();
        newProfile.setAge(index+20);
        newProfile.setFirstName(("FName"+String.valueOf(index)));
        newProfile.setLastName(("LName"+String.valueOf(index)));
        newProfile.setSocialSecurityNumber((String.valueOf(index)).repeat(3));
        Address workAddress = new Address();
        workAddress.setCity("workCity"+String.valueOf(index));
        workAddress.setState("workState"+String.valueOf(index));
        workAddress.setStreetAddress("workStreetAddr"+String.valueOf(index));
        workAddress.setPhoneNumber(String.valueOf(index).repeat(8));
        workAddress.setUnitNumber(String.valueOf(index).repeat(1));
        workAddress.setZipCode("workZipCode"+String.valueOf(index));
        newProfile.setWorkAddress(workAddress);
        Address homeAddress = new Address();
        homeAddress.setCity("homeCity"+String.valueOf(index));
        homeAddress.setState("homeState"+String.valueOf(index));
        homeAddress.setStreetAddress("homeStreetAddr"+String.valueOf(index));
        homeAddress.setPhoneNumber(String.valueOf(index).repeat(6));
        homeAddress.setUnitNumber(String.valueOf(index).repeat(2));
        homeAddress.setZipCode(String.valueOf(index));
        newProfile.setHomeAddress(homeAddress);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        btnMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(176, 190, 197));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnMng.setText("Go to Main Menu");
        btnMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngActionPerformed(evt);
            }
        });
        jSplitPane1.setTopComponent(btnMng);

        userProcessContainer.setBackground(new java.awt.Color(176, 190, 197));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngActionPerformed
        // TODO add your handling code here:
        ProfileMngWorkAreaJPanel panel = new ProfileMngWorkAreaJPanel(userProcessContainer, profileDirectory);
        userProcessContainer.add("AccountMngWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMng;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
